import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import QueryClientProviderApp from '@/providers/QueryClientApp/queryClientApp'
import Header from './components/Header/header'
import Wrapper from './components/Wrapper/wrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <QueryClientProviderApp>
        <body className={inter.className}>
          <Header />
          <Wrapper className="bg-fern-50 min-h-screen">{children}</Wrapper>
        </body>
      </QueryClientProviderApp>
    </html>
  )
}
